###  FBV
GET http://127.0.0.1:8080/version/
Accept: application/json


###  FBV
GET http://127.0.0.1:8080/books/
Accept: application/json

###  FBV
POST http://127.0.0.1:8080/books/
Accept: application/json


### CBV

### get
GET http://127.0.0.1:8080/book/
Accept: application/json


### POST
POST http://127.0.0.1:8080/book/
Accept: application/json


### PUT
PUT http://127.0.0.1:8080/book/
Accept: application/json

### DEL
DELETE http://127.0.0.1:8080/book/
Accept: application/json


### CBV   rest APIView

### get
GET http://127.0.0.1:8080/bookAPIview/?name=pcw&age=20
Accept: application/json


### POST
POST http://127.0.0.1:8080/bookAPIview/
Accept: application/json

{"name": "pcw"}

### PUT
PUT http://127.0.0.1:8080/bookAPIview/
Accept: application/json

{"name": "pcw"}

### DEL
DELETE http://127.0.0.1:8080/bookAPIview/
Accept: application/json

###

### CBV   rest APIView  db

### get
GET http://127.0.0.1:8080/bookview/
Accept: application/json


###
POST http://127.0.0.1:8080/bookview/
Accept: application/json

{
    "title": "jq快速入门",
    "price": 100,
    "pub_date": "2019-06-13"
}



###
GET http://127.0.0.1:8080/bookview/6
Accept: application/json


###
PUT http://127.0.0.1:8080/bookview/13
Accept: application/json

{
    "title": "oracle高级编程3",
    "price": 289
}


###
DELETE http://127.0.0.1:8080/bookview/5
Accept: application/json








### CBV   rest APIView  db generic

### get
GET http://127.0.0.1:8080/publish/
Accept: application/json


###
POST http://127.0.0.1:8080/publish/
Accept: application/json

{
    "name": "南京出版社",
    "city": "南京"
}



###
GET http://127.0.0.1:8080/publish/1
Accept: application/json


###
PUT http://127.0.0.1:8080/publish/4
Accept: application/json

{
    "name": "浙江出版社",
    "city": "浙江市"
}


###
DELETE http://127.0.0.1:8080/publish/5
Accept: application/json




### CBV   rest APIView  db generic  复制 author

### get
GET http://127.0.0.1:8080/author/
Accept: application/json


###
POST http://127.0.0.1:8080/author/
Accept: application/json

{
    "name": "周树人",
    "age": 30
}



###
GET http://127.0.0.1:8080/author/2
Accept: application/json


###
PUT http://127.0.0.1:8080/author/3
Accept: application/json

{
    "name": "鲁迅",
    "age": 30
}


###
DELETE http://127.0.0.1:8080/author/3
Accept: application/json


