###  FBV
GET http://127.0.0.1:8080/version/
Accept: application/json


###  FBV
GET http://127.0.0.1:8080/books/
Accept: application/json

###  FBV
POST http://127.0.0.1:8080/books/
Accept: application/json


### CBV

### get
GET http://127.0.0.1:8080/book/
Accept: application/json


### POST
POST http://127.0.0.1:8080/book/
Accept: application/json


### PUT
PUT http://127.0.0.1:8080/book/
Accept: application/json

### DEL
DELETE http://127.0.0.1:8080/book/
Accept: application/json


### CBV   rest APIView

### get
GET http://127.0.0.1:8080/bookAPIview/?name=pcw&age=20
Accept: application/json


### POST
POST http://127.0.0.1:8080/bookAPIview/
Accept: application/json

{"name": "pcw"}

### PUT
PUT http://127.0.0.1:8080/bookAPIview/
Accept: application/json

{"name": "pcw"}

### DEL
DELETE http://127.0.0.1:8080/bookAPIview/
Accept: application/json

###

### CBV   rest APIView  db

### get
GET http://127.0.0.1:8080/bookview/
Accept: application/json