###  FBV
GET http://127.0.0.1:8080/books/
Accept: application/json

###  FBV
POST http://127.0.0.1:8080/books/
Accept: application/json


### CBV

### get
GET http://127.0.0.1:8080/book/
Accept: application/json


### POST
POST http://127.0.0.1:8080/book/
Accept: application/json


### PUT
PUT http://127.0.0.1:8080/book/
Accept: application/json

### DEL
DELETE http://127.0.0.1:8080/book/
Accept: application/json

###


